#
# File with xml-files tags and attributes names
#

MODULE_TAG = 'module'
MODULE_ATTRIBUTE_ID = 'id'
MODULE_ATTRIBUTE_NAME = 'name'
MODULE_ATTRIBUTE_FOLDER = 'folder'
MODULE_ATTRIBUTE_FILE = 'file'
MODULE_ATTRIBUTE_ICON = 'icon'

MODULES_GROUP_TAG = 'group'
MODULES_GROUP_ATTRIBUTE_ID = 'id'
MODULES_GROUP_ATTRIBUTE_NAME = 'name'
MODULES_GROUP_ATTRIBUTE_FOLDER = 'folder'
MODULES_GROUP_ATTRIBUTE_ICON = 'icon'

INPUT_PARAMETERS_TAG = 'input_parameters'
USER_PARAMETERS_TAG = 'user_parameters'
OUTPUT_PARAMETERS_TAg = 'output_parameters'

PARAMETER_TAG = 'parameter'
PARAMETER_ATTRIBUTE_NAME = 'name'
PARAMETER_ATTRIBUTE_TYPE = 'type'
PARAMETER_ATTRIBUTE_DEFAULT = 'default'

REALIZATIONS_TAG = 'realizations'

REALIZATION_TAG = 'realization'
REALIZATION_ATTRIBUTE_ID = 'id'
REALIZATION_ATTRIBUTE_LANGUAGE = 'language'
REALIZATION_ATTRIBUTE_TYPE = 'type'
REALIZATION_ATTRIBUTE_FOLDER = 'folder'
REALIZATION_ATTRIBUTE_FILE = 'file'
REALIZATION_ATTRIBUTE_METHOD = 'method'